# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  goforum:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      # - ./projet/.env:/projet/.env
      # - ./projet/goForumDataBase.db:/data/goForumDataBase.db
      # - ./projet/cert.pem:/cert.pem
      # - ./projet/key.pem:/key.pem
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}

      - CERT_FILE=${CERT_FILE}
      - CERT_KEY_FILE=${CERT_KEY_FILE}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    restart: unless-stopped

volumes:
  sqlite-data:
    # Volume persistant pour stocker la base de données SQLite